### ISSUE TITLE
定时启动报错

### ISSUE THREAD

**Issue by UU0510** [DoctorReid/StarRailOneDragon#139]
定时启动1选择"4",定时启动2选择"无", 脚本会直接启动, 并且报错:

IndexError: list index out of range
[15:43:50] [scheduler.py 55] [ERROR]: 定时任务出错
Traceback (most recent call last):
  File "gui\scheduler.py", line 53, in _run_schedule
  File "schedule\__init__.py", line 822, in run_pending
  File "schedule\__init__.py", line 100, in run_pending
  File "schedule\__init__.py", line 172, in _run_job
  File "schedule\__init__.py", line 693, in run
  File "gui\one_stop_view.py", line 409, in _update_running_app_name
  File "sr\app\one_stop_service.py", line 137, in current_execution_desc
IndexError: list index out of range

**Comment by DoctorReid** [comment]
@UU0510 感觉是4点的时候刚好前一天的运行记录还没刷新到，先试试设置 5点

**Comment by DoctorReid** [comment]
新版本改用了整点1秒后再启动，应该避免了这个问题

**Comment by UU0510** [comment]
大佬, 我定时四点启动显示回到主界面失败, 可能是卡在了月卡领取界面?

**Comment by DoctorReid** [comment]
附上日志看看

**Comment by UU0510** [comment]
[04:00:02] [context.py 231] [INFO]: 加载工具中
[04:00:02] [context.py 219] [INFO]: 加载图片匹配器完毕
[04:00:02] [context.py 227] [INFO]: 加载OCR识别器完毕
[04:00:02] [context.py 211] [INFO]: 加载游戏控制器完毕
[04:00:02] [context.py 237] [INFO]: 加载工具完毕
[04:00:02] [__init__.py 222] [INFO]: 最终加载 47 条线路 过滤已完成 0 条 使用名单 None
[04:00:09] [__init__.py 248] [ERROR]: 指令[ 回到主界面 ] 执行失败 返回状态 失败
[04:00:09] [__init__.py 248] [ERROR]: 指令[ 选择配队 ] 执行失败 返回状态 失败
[04:00:09] [__init__.py 248] [ERROR]: 指令[ 锄大地 ] 执行失败 返回状态 失败
[04:00:09] [__init__.py 246] [INFO]: 指令[ 一条龙 ] 执行成功 返回状态 成功
[04:00:09] [context.py 112] [INFO]: 停止运行
[04:00:09] [context.py 128] [INFO]: 暂停运行

**Comment by DoctorReid** [comment]
这是游戏没有关，然后4点时候定时启动的情况是吗

**Comment by UU0510** [comment]
是的, 游戏界面停在月卡领取的界面

**Comment by DoctorReid** [comment]
了解，暂时可以使用运行后关闭游戏，下一次启动重新进游戏应该就没事了

**Comment by DoctorReid** [comment]
v1.1.0 已解决
