### ISSUE TITLE
模拟宇宙精英关卡秘技开怪报错

### ISSUE THREAD

**Issue by UU0510** [DoctorReid/StarRailOneDragon#187]
[01:51:39] [__init__.py 675] [INFO]: 指令[ 模拟宇宙 区域-精英 ] 节点 执行路线指令 返回状态 成功
[01:51:40] [__init__.py 675] [INFO]: 指令[ 模拟宇宙 挑战精英首领 ] 节点 检测敌人 返回状态 成功
[01:51:40] [__init__.py 252] [INFO]: 指令[ 检测秘技点数 ] 执行成功 返回状态 4
[01:51:40] [__init__.py 675] [INFO]: 指令[ 使用秘技 进入战斗 ] 节点 检测秘技点 返回状态 成功
[01:51:41] [__init__.py 252] [INFO]: 指令[ 组队角色判断 1 ] 执行成功 返回状态 ruanmei
[01:51:41] [__init__.py 252] [INFO]: 指令[ 组队角色判断 2 ] 执行成功 返回状态 himeko
[01:51:41] [__init__.py 252] [INFO]: 指令[ 组队角色判断 3 ] 执行成功 返回状态 topaznumby
[01:51:42] [__init__.py 252] [INFO]: 指令[ 组队角色判断 4 ] 执行成功 返回状态 fuxuan
[01:51:42] [__init__.py 675] [INFO]: 指令[ 使用秘技 进入战斗 ] 节点 获取角色列表 返回状态 成功
[01:51:42] [__init__.py 162] [ERROR]: 指令[ 使用秘技 进入战斗 ] 执行出错
Traceback (most recent call last):
  File "sr\operation\__init__.py", line 148, in execute
  File "sr\operation\__init__.py", line 676, in _execute_one_round
AttributeError: 'NoneType' object has no attribute 'status'
[01:51:42] [__init__.py 162] [ERROR]: 指令[ 使用秘技 进入战斗 ] 执行出错
Traceback (most recent call last):
  File "sr\operation\__init__.py", line 148, in execute
  File "sr\operation\__init__.py", line 676, in _execute_one_round
AttributeError: 'NoneType' object has no attribute 'status'
[01:51:42] [__init__.py 254] [ERROR]: 指令[ 使用秘技 进入战斗 ] 执行失败 返回状态 异常
[01:51:42] [__init__.py 675] [INFO]: 指令[ 模拟宇宙 挑战精英首领 ] 节点 秘技进入战斗 返回状态 异常
[01:51:42] [__init__.py 254] [ERROR]: 指令[ 模拟宇宙 挑战精英首领 ] 执行失败 返回状态 异常
[01:51:42] [__init__.py 675] [INFO]: 指令[ 模拟宇宙 区域-精英 路线后 ] 节点 战斗 返回状态 异常
[01:51:42] [__init__.py 254] [ERROR]: 指令[ 模拟宇宙 区域-精英 路线后 ] 执行失败 返回状态 异常
[01:51:42] [__init__.py 675] [INFO]: 指令[ 模拟宇宙 区域-精英 ] 节点 区域特殊指令 返回状态 异常
[01:51:42] [__init__.py 254] [ERROR]: 指令[ 模拟宇宙 区域-精英 ] 执行失败 返回状态 异常
[01:51:42] [__init__.py 675] [INFO]: 指令[ 模拟宇宙 第六世界 挑战楼层 ] 节点 区域 返回状态 异常
[01:51:42] [__init__.py 254] [ERROR]: 指令[ 模拟宇宙 第六世界 挑战楼层 ] 执行失败 返回状态 异常
[01:51:42] [__init__.py 675] [INFO]: 指令[ 模拟宇宙 第六世界 ] 节点 挑战楼层 返回状态 异常
[01:51:42] [__init__.py 254] [ERROR]: 指令[ 模拟宇宙 第六世界 ] 执行失败 返回状态 异常
[01:51:42] [__init__.py 675] [INFO]: 指令[ 模拟宇宙 ] 节点 通关 返回状态 异常

**Comment by DoctorReid** [comment]
哪个版本

**Comment by UU0510** [comment]
97和99都是这样

**Comment by DoctorReid** [comment]
大概知道了，4个角色都没有攻击类秘技时候就会出现这个问题
