### ISSUE TITLE
锄大地、校准、模拟宇宙均无法启动

### ISSUE THREAD

**Issue by phynoworld** [DoctorReid/StarRailOneDragon#262]
# 使用版本

1.2.4

# 问题应用

锄大地、校准、模拟宇宙均无法启动

# 问题描述

一条龙打开的锄大地和模拟宇宙，最小化后按F9只会不停的打开关闭菜单，就算人工按M点开地图也只打一个怪就不动了,系统是WIN10，没有开启HDR
日志如下:

[02:01:18] [context.py 484] [INFO]: 加载工具中
[02:01:18] [context.py 472] [INFO]: 加载图片匹配器完毕
[02:01:18] [context.py 480] [INFO]: 加载OCR识别器完毕
[02:01:18] [context.py 464] [INFO]: 加载游戏控制器完毕
[02:01:18] [context.py 490] [INFO]: 加载工具完毕
[02:01:19] [__init__.py 709] [INFO]: 指令[ 一条龙 ] 节点 初始化账号列表 返回状态 成功
[02:01:19] [__init__.py 709] [INFO]: 指令[ 一条龙 ] 节点 切换账号运行 返回状态 成功
[02:01:19] [__init__.py 174] [ERROR]: 指令[ 一条龙 ] 执行出错
Traceback (most recent call last):
  File "sr\operation\__init__.py", line 160, in execute
  File "sr\operation\__init__.py", line 700, in _execute_one_round
  File "sr\app\one_stop_service\one_stop_service_app.py", line 150, in _run_app_in_current_account
  File "sr\app\application_base.py", line 61, in execute
  File "sr\operation\__init__.py", line 142, in execute
  File "sr\app\world_patrol\world_patrol_app.py", line 60, in _init_before_execute
  File "sr\app\world_patrol\world_patrol_route.py", line 426, in load_all_route_id
  File "sr\app\world_patrol\world_patrol_route.py", line 54, in __init__
AssertionError
[02:01:19] [sim_uni_app.py 172] [INFO]: 本日通关次数 0 本周通关次数 0
[02:01:19] [__init__.py 709] [INFO]: 指令[ 模拟宇宙 ] 节点 检查运行次数 返回状态 成功
[02:01:19] [__init__.py 709] [INFO]: 指令[ 模拟宇宙 ] 节点 检查初始画面 返回状态 大世界
[02:01:20] [open_phone_menu.py 28] [INFO]: 尝试打开菜单
[02:01:21] [open_phone_menu.py 28] [INFO]: 尝试打开菜单
[02:01:22] [open_phone_menu.py 28] [INFO]: 尝试打开菜单
[02:01:23] [context.py 380] [INFO]: 暂停运行
[02:01:57] [context.py 384] [INFO]: 恢复运行
[02:01:58] [open_phone_menu.py 28] [INFO]: 尝试打开菜单
[02:01:59] [open_phone_menu.py 28] [INFO]: 尝试打开菜单
[02:02:00] [context.py 365] [INFO]: 停止运行
[02:02:00] [context.py 380] [INFO]: 暂停运行
[02:02:00] [__init__.py 266] [ERROR]: 指令[ 打开菜单 ] 执行失败 返回状态 人工结束
[02:02:00] [__init__.py 709] [INFO]: 指令[ 模拟宇宙 ] 节点 菜单 返回状态 人工结束
[02:02:00] [__init__.py 266] [ERROR]: 指令[ 模拟宇宙 ] 执行失败 返回状态 人工结束
[02:02:00] [__init__.py 709] [INFO]: 指令[ 一条龙 ] 节点 运行应用 返回状态 人工结束
[02:02:00] [__init__.py 266] [ERROR]: 指令[ 一条龙 ] 执行失败 返回状态 人工结束

**Comment by yinghaodang** [comment]
这个是因为锄大地的配置文件有较大变动，自动更新出bug了。重新解压校准可以解决。

**Comment by phynoworld** [comment]
> 这个是因为锄大地的配置文件有较大变动，自动更新出bug了。重新解压校准可以解决。

重新解压后也没有解决，校准时仍然不停打开关闭菜单。
日志如下：
[23:26:34] [context.py 485] [INFO]: 加载工具中
[23:26:34] [context.py 473] [INFO]: 加载图片匹配器完毕
[23:26:34] [context.py 481] [INFO]: 加载OCR识别器完毕
[23:26:34] [context.py 465] [INFO]: 加载游戏控制器完毕
[23:26:34] [context.py 491] [INFO]: 加载工具完毕
[23:26:35] [calibrator.py 32] [INFO]: [小地图定位校准] 开始
[23:26:35] [open_map.py 46] [INFO]: 当前大地图所处星球 None
[23:26:35] [open_map.py 51] [INFO]: 尝试返回上级菜单
[23:26:38] [open_map.py 46] [INFO]: 当前大地图所处星球 None
[23:26:38] [open_map.py 51] [INFO]: 尝试返回上级菜单
[23:26:40] [open_map.py 46] [INFO]: 当前大地图所处星球 None
[23:26:40] [open_map.py 51] [INFO]: 尝试返回上级菜单

另外，运行锄大地时也时开始就不停平A卡住

**Comment by DoctorReid** [comment]
开始后不停打开关闭手机

- 游戏分辨率只能是16:9
- 全屏模式时，屏幕分辨率也需要时16:9
- 关闭显示HDR
- 游戏中右上角的角色图标不能有红点
- 关闭帧率显示或者其它类似会悬浮在画面上的内容
