### ISSUE TITLE
米游蛇登录功能：获取、输入验证码后报错无法登入。

### ISSUE THREAD

**Issue by Yuuenn** [DoctorReid/StarRailOneDragon#265]
# 使用版本

1.2.5

# 问题设置

设置-米游蛇-登录

# 问题描述

获取、输入验证码后报错无法登入

```
[10:11:38] [one_dragon_mys_config.py 62] [INFO]: 2.前往米哈游官方登录页，获取验证码（不要登录！）
[10:12:08] [one_dragon_mys_config.py 71] [INFO]: 用户 ---------- 成功获取 login_ticket: ----------
[10:12:09] [one_dragon_mys_config.py 84] [INFO]: 用户 ---------- 成功获取 device_fp: ----------
[10:12:17] [common.py 1004] [ERROR]: 通过 login_ticket 获取 stoken: 服务器没有正确返回
Traceback (most recent call last):
  File "sr\mystools\api\common.py", line 997, in get_multi_token_by_login_ticket
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sr\mystools\api\common.py", line 985, in get_multi_token_by_login_ticket
  File "tenacity\_asyncio.py", line 71, in __anext__
  File "tenacity\__init__.py", line 326, in iter
tenacity.RetryError: RetryError[<Future at 0x207bd02bf90 state=finished raised IndexError>]
[10:12:24] [common.py 955] [INFO]: 通过短信验证码获取 login_ticket - 验证码错误，但你可以再次尝试登录
[10:13:08] [one_dragon_mys_config.py 71] [INFO]: 用户 ---------- 成功获取 login_ticket: Z----------
[10:13:09] [one_dragon_mys_config.py 84] [INFO]: 用户 ---------- 成功获取 device_fp: ----------
[10:13:17] [common.py 1004] [ERROR]: 通过 login_ticket 获取 stoken: 服务器没有正确返回
Traceback (most recent call last):
  File "sr\mystools\api\common.py", line 997, in get_multi_token_by_login_ticket
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sr\mystools\api\common.py", line 985, in get_multi_token_by_login_ticket
  File "tenacity\_asyncio.py", line 71, in __anext__
  File "tenacity\__init__.py", line 326, in iter
tenacity.RetryError: RetryError[<Future at 0x207bd02df90 state=finished raised IndexError>]
```

**Comment by DoctorReid** [comment]
是否已经在米游社创建账号

**Comment by 67762961** [comment]
我也有这个问题，我肯定是有账号的，尝试了关闭米游社设备验证的设置也不行，日志内容跟他一样的

**Comment by soulans** [comment]
我也是。
