### ISSUE TITLE
[问题反馈] [开拓力] 历战余响选择支援时报错

### ISSUE THREAD

**Issue by fengziX** [DoctorReid/StarRailOneDragon#397]
### 使用版本

2.6.1

### 问题副本

历战余响

### 问题描述

选择支援时报错

### 游戏截图

![QQ20241110-212035](https://github.com/user-attachments/assets/f0106956-6ddb-4b00-abe4-64312b8a1183)
![QQ20241110-212048](https://github.com/user-attachments/assets/c2927673-12dd-4a40-9a55-4a5f4eadcbdb)

### 运行日志

指令[ 历战余响 不死的神实 次数 3 ] 节点 点击挑战 返回状态 挑战按钮
指令[ 历战余响 不死的神实 次数 3 ] 节点 点击挑战后确认 返回状态 成功
指令[ 选择配队 ] 节点 检测游戏窗口 返回状态 成功
指令[ 选择配队 ] 节点 选择配队 返回状态 成功
指令[ 选择配队 ] 执行成功 返回状态 成功
指令[ 历战余响 不死的神实 次数 3 ] 节点 选择配队 返回状态 成功
指令[ 选择支援 ] 节点 检测游戏窗口 返回状态 成功
指令[ 选择支援 ] 节点 等待画面加载 返回状态 需要支援角色
指令[ 选择支援 ] 节点 点击支援 返回状态 支援按钮
指令[ 选择支援 ] 执行出错 相关截图保存至 ChooseSupportInTeam_1731244781102 Traceback (most recent call last): File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 69, in click_avatar pos = self._get_character_pos(screen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 133, in _get_character_pos template.kps, template.desc, ^^^^^^^^^^^^ AttributeError: 'TemplateInfo' object has no attribute 'kps'
指令[ 选择支援 ] 执行出错 相关截图保存至 ChooseSupportInTeam_1731244781784 Traceback (most recent call last): File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 69, in click_avatar pos = self._get_character_pos(screen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 133, in _get_character_pos template.kps, template.desc, ^^^^^^^^^^^^ AttributeError: 'TemplateInfo' object has no attribute 'kps'
指令[ 选择支援 ] 执行出错 相关截图保存至 ChooseSupportInTeam_1731244782444 Traceback (most recent call last): File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 69, in click_avatar pos = self._get_character_pos(screen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 133, in _get_character_pos template.kps, template.desc, ^^^^^^^^^^^^ AttributeError: 'TemplateInfo' object has no attribute 'kps'
指令[ 选择支援 ] 执行出错 相关截图保存至 ChooseSupportInTeam_1731244783064 Traceback (most recent call last): File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 69, in click_avatar pos = self._get_character_pos(screen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 133, in _get_character_pos template.kps, template.desc, ^^^^^^^^^^^^ AttributeError: 'TemplateInfo' object has no attribute 'kps'
指令[ 选择支援 ] 执行出错 相关截图保存至 ChooseSupportInTeam_1731244783682 Traceback (most recent call last): File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 69, in click_avatar pos = self._get_character_pos(screen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 133, in _get_character_pos template.kps, template.desc, ^^^^^^^^^^^^ AttributeError: 'TemplateInfo' object has no attribute 'kps'
指令[ 选择支援 ] 执行出错 相关截图保存至 ChooseSupportInTeam_1731244784346 Traceback (most recent call last): File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 69, in click_avatar pos = self._get_character_pos(screen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 133, in _get_character_pos template.kps, template.desc, ^^^^^^^^^^^^ AttributeError: 'TemplateInfo' object has no attribute 'kps'
指令[ 选择支援 ] 执行出错 相关截图保存至 ChooseSupportInTeam_1731244784956 Traceback (most recent call last): File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 69, in click_avatar pos = self._get_character_pos(screen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 133, in _get_character_pos template.kps, template.desc, ^^^^^^^^^^^^ AttributeError: 'TemplateInfo' object has no attribute 'kps'
指令[ 选择支援 ] 执行出错 相关截图保存至 ChooseSupportInTeam_1731244785570 Traceback (most recent call last): File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 69, in click_avatar pos = self._get_character_pos(screen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 133, in _get_character_pos template.kps, template.desc, ^^^^^^^^^^^^ AttributeError: 'TemplateInfo' object has no attribute 'kps'
指令[ 选择支援 ] 执行出错 相关截图保存至 ChooseSupportInTeam_1731244786172 Traceback (most recent call last): File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 69, in click_avatar pos = self._get_character_pos(screen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 133, in _get_character_pos template.kps, template.desc, ^^^^^^^^^^^^ AttributeError: 'TemplateInfo' object has no attribute 'kps'
指令[ 选择支援 ] 执行出错 相关截图保存至 ChooseSupportInTeam_1731244786822 Traceback (most recent call last): File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 295, in execute round_result: OperationRoundResult = self._execute_one_round() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\one_dragon\base\operation\operation.py", line 367, in _execute_one_round current_round_result: OperationRoundResult = self._current_node.op_method(self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 69, in click_avatar pos = self._get_character_pos(screen) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Download\Github\StarRail-OneDragon\src\sr_od\challenge_mission\choose_support_in_team.py", line 133, in _get_character_pos template.kps, template.desc, ^^^^^^^^^^^^ AttributeError: 'TemplateInfo' object has no attribute 'kps'

**Comment by DoctorReid** [comment]
修复了 更新下代码
